version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    command: python src/app.py
    volumes:
      - ./.env:/app/.env
      - temp_uploads:/app/temp_uploads
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - BACKEND_URL=http://backend:5001
    command: python src/gradio_interface.py
    volumes:
      - ./.env:/app/.env
      - temp_uploads:/app/temp_uploads
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  temp_uploads: